### ISSUE TITLE
std::min(a,b) vs std::min<DualReal>(a,b)

### ISSUE THREAD

**Issue by dschwen** [roystgnr/MetaPhysicL#44]
Why does 

```
DualReal a=1, b=2;
std::min(a, b)
```

compile fine, but 

```
DualReal a=1, b=2;
std::min<DualReal>(a, b)
```

gives an `error: call to 'min' is ambiguous`?! If anything the explicitly passed typename should make it less ambiguous. This is not a "for fun" question, but trips me up trying to instantiate a class from an external library, which has plenty of `std:XXX<T>(...)` type calls. Ping @lindsayad 

P.S.: `DualReal` is the MetaPhysicL dual number type used in MOOSE

**Comment by dschwen** [comment]
Mh, I think my best option is to patch upstream to rely on automatic template parameter deduction (first variant)...

**Comment by roystgnr** [comment]
Does the compiler tell you which instantiations it can't decide between?

**Comment by dschwen** [comment]
Hold on to your hat!

```
/opt/moose/llvm-6.0.1/include/c++/v1/algorithm:2652:1: note: candidate function [with _Tp = MetaPhysicL::DualNumber<double, MetaPhysicL::NumberArray<50, double> >]
min(const _Tp& __a, const _Tp& __b)
^
/Users/schwd/Programs/libmesh/installed/include/metaphysicl/dualnumber.h:642:830: note: candidate function [with T = MetaPhysicL::DualNumber<double, MetaPhysicL::NumberArray<50, double> >, T2 = double, D = MetaPhysicL::NumberArray<50, double>]
template <typename T, typename D, typename T2, typename D2> inline typename CompareTypes<DualNumber<T,D>,DualNumber<T2,D2> >::supertype min (const DualNumber<T,D>& a, const DualNumber<T2,D2>& b) { typedef typename CompareTypes<T,T2>::supertype TS; typedef typename CompareTypes<DualNumber<T,D>,DualNumber<T2,D2> >::supertype type; TS funcval = std::min(a.value(), b.value()); return type(funcval, (a.value() > b.value()) ? b.derivatives() : a.derivatives()); } template <typename T, typename D> inline DualNumber<T,D> min (const DualNumber<T,D>& a, const DualNumber<T,D>& b) { T funcval = std::min(a.value(), b.value()); return DualNumber<T,D>(funcval, (a.value() > b.value()) ? b.derivatives() : a.derivatives()); } template <typename T, typename T2, typename D> inline typename CompareTypes<DualNumber<T2,D>,T,true>::supertype min (const T& a, const DualNumber<T2,D>& b) { typedef typename CompareTypes<DualNumber<T2,D>,T,true>::supertype type; type newa(a); return std::min(newa, b); } template <typename T, typename T2, typename D> inline typename CompareTypes<DualNumber<T,D>,T2>::supertype min (const DualNumber<T,D>& a, const T2& b) { typedef typename CompareTypes<DualNumber<T,D>,T2>::supertype type; type newb(b); return std::min(a, newb); }
```

**Comment by dschwen** [comment]
I like the first one. The second one scares me.

**Comment by dschwen** [comment]
I encountered a similar problem in https://github.com/libMesh/libmesh/pull/2090 in the trailing return type stuff where I had to use ` -> decltype(std::abs(T(0)))` instead of ` -> decltype(std::abs<T>(0))`.

**Comment by roystgnr** [comment]
What compiler are you using?

> Mh, I think my best option is to patch upstream to rely on automatic template parameter deduction (first variant)...

From your perspective I can't exactly disagree.  I'd still appreciate help figuring out the problem so we can avoid letting it bite other people in the future, though.

So here's what baffling me: In that error message it only says "candidate function" once, but then it lists *three* candidate functions (the second of which should be what resolution prefers).  I think my macro "cleverness" might be confusing the error printing mechanisms...

> I encountered a similar problem in libMesh/libmesh#2090 in the trailing return type stuff where I had to use -> decltype(std::abs(T(0))) instead of -> decltype(std::abs<T>(0)).

This is more baffling but probably more productive to investigate; since it's not a binary function there's fewer overloads to worry about (just one with a const reference and one with a move reference), and things should be even less ambiguous.
...
But it looks like I can replicate it, at least on my laptop with gcc 5.4.  Let me look at it.

**Comment by roystgnr** [comment]
Huh.  With abs the *only* ```abs<T>(NumberArray<)``` overload from MetaPhysicL that I see suggested is ```abs<T>(const DualNumber<std::complex<T>>&)```.  And even though that's obviously ill-suited in terms of function arguments, it's forcing me to notice that it's the *only* matching candidate in terms of template arguments.  Everything that's designed to operate on ```NumberArray<N,T>``` naturally has to template around both N and T.

... and in the abs case it looks like even the standard library doesn't use templating for non-complex cases!  My compiler is only seeing the templated version in the ```complex``` header, and it seems to be conforming in this regard; the C++ standard lists individual declarations for float/double/long double (and in C++11 int/long/long long), not a templated declaration for anything but std::complex.

So for ```std::abs```, "fix it upstream" really *would* be the right solution.

But ```std::min``` is legitimately declared as a template function with one template argument, and there is a legitimate reason for user code to make that argument explicit (to choose what conversion to use or to disambiguate things when the two function argument types differ), and yet I don't know of any way to compatibly add an overload here for a user data type which is itself templated.  If that's not just my ignorance talking, if there actually *isn't* a way to add such an overload, then "fix it upstream" might be justifiable, since any other templated data type would have the same problem and be unable to fix it.

**Comment by roystgnr** [comment]
Oh, wonderful.  Not only is there no way to add such an overload, but even the idiom we're using now is technically non-conforming (although it's ridiculously well-supported, since [even Boost does it](https://groups.google.com/forum/#!topic/comp.lang.c++.moderated/s5b-2tfc3IE%5B1-25%5D)).  We're using ["the fingers-crossed solution" to the problem](https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Non-throwing_swap#Caveats):

> 1. Standard-compliant solution. Leveraging on Koenig lookup, define an overloaded swap function template in the same namespace as that of the class being swapped. Not all compilers may support this correctly, but this solution is compliant to the standard.[2]
> 2. Fingers-crossed solution. Partially specialize std::swap and ignore the fact that this is technically undefined behavior, hoping that nothing will happen and wait for a fix in the next language standard.

But whereas the fingers-crossed solution breaks any code using ```foo<ExplicitType>``` instead of letting the type be deduced from arguments, even the standard-compliant solution would break any code using ```std::foo``` instead of letting the namespace be deduced from arguments.  So there's no way to get around a need to change upstream, sorry.

**Comment by dschwen** [comment]
Ok, PR is made. I'm using clang 6.0.1 by the way.

**Comment by roystgnr** [comment]
Thanks.  We can wait to close this until you've haggled with upstream.

I could be talked into moving our overloads from std:: to MetaPhysicL:: (from option 2 to option 1), at least as a compile-time option, but it seems that's really our only other option here, and it wouldn't actually help us deal with any unexpected idioms upstream libraries, just with unexpected strictness in odd compilers.

**Comment by ArashPartow** [comment]
@roystgnr / @dschwen  - Don't remember exactly, but I think the explicit specialisation was required to get around a compiler bug in msvc2003 when one is using a custom numeric type, that hasn't exposed min/max etc in the std namespace as ADL was not functioning correctly for some reason.

That being said, I'll look into it a little more.

**Comment by dschwen** [comment]
Oh, I hadn't noticed https://github.com/ArashPartow/exprtk-custom-types . This is super helpful as I've so far been figuring out from compiler errors which specializations and overloads I need to implement for the dual numbers :-)

As for masv, I noticed a bunch of ifdefs checking for msvc in the code already (some just suppressing warnings with pragmas, but two implementing shims for erf and erfc). That might be a way to go with min/max as well.

Another option would of course be to add a specialization for the various functions calling std::min and std::max on our side...

**Comment by ArashPartow** [comment]
@dschwen  - I if you were to implement an ExprTk adaptor for the numeric type you are using/specialising on, the compilation issues you're seeing will most likely be resolved - and it will be a much cleaner solution. 

This can be done simply by taking one of the examples from above and performing a search-n-replace for the used numeric type with your specific numeric type. Then to make sure you include the new adaptor header before the line you include the ExprTk header.
